import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout from "./components/Layout";
import CustomHead from "./components/Head";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ServerLayout({ children }) {
  return (
    <html lang="en">
        <CustomHead  />
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Layout>
      
          {children}
        
        </Layout>
      </body>
    </html>
  );
}